// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoweP_EoqBvjtUSDTOS38YnYggvVMjww8',
    appId: '1:75520365481:android:6c498ab18828218aca6ab8',
    messagingSenderId: '75520365481',
    projectId: 'login-f6ba6',
    storageBucket: 'login-f6ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Yd9VuKBHKmgnn8OkGv4alLU0t8MnWng',
    appId: '1:75520365481:ios:6e9b775ac81ad839ca6ab8',
    messagingSenderId: '75520365481',
    projectId: 'login-f6ba6',
    storageBucket: 'login-f6ba6.appspot.com',
    androidClientId: '75520365481-tfscbls6541spce28ip0ncqpbnncabas.apps.googleusercontent.com',
    iosClientId: '75520365481-28r6tvlrnpevo2oa6tlp2in408d7q4m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMerv7LbEUdbJd4dEgvVAj1XXzPAkyd2U',
    appId: '1:75520365481:web:2eac6f83e4c76d20ca6ab8',
    messagingSenderId: '75520365481',
    projectId: 'login-f6ba6',
    authDomain: 'login-f6ba6.firebaseapp.com',
    storageBucket: 'login-f6ba6.appspot.com',
  );

}